condor_submit ./condorSub/cat0/gof_study_10.submit
condor_submit ./condorSub/cat1/gof_study_10.submit
condor_submit ./condorSub/cat0/gof_study_11.submit
condor_submit ./condorSub/cat1/gof_study_11.submit
condor_submit ./condorSub/cat0/gof_study_12.submit
condor_submit ./condorSub/cat1/gof_study_12.submit
condor_submit ./condorSub/cat0/gof_study_13.submit
condor_submit ./condorSub/cat1/gof_study_13.submit
condor_submit ./condorSub/cat0/gof_study_14.submit
condor_submit ./condorSub/cat1/gof_study_14.submit
condor_submit ./condorSub/cat0/gof_study_15.submit
condor_submit ./condorSub/cat1/gof_study_15.submit
condor_submit ./condorSub/cat0/gof_study_16.submit
condor_submit ./condorSub/cat1/gof_study_16.submit
condor_submit ./condorSub/cat0/gof_study_17.submit
condor_submit ./condorSub/cat1/gof_study_17.submit
condor_submit ./condorSub/cat0/gof_study_18.submit
condor_submit ./condorSub/cat1/gof_study_18.submit
condor_submit ./condorSub/cat0/gof_study_19.submit
condor_submit ./condorSub/cat1/gof_study_19.submit
condor_submit ./condorSub/cat0/gof_study_20.submit
condor_submit ./condorSub/cat1/gof_study_20.submit
condor_submit ./condorSub/cat0/gof_study_21.submit
condor_submit ./condorSub/cat1/gof_study_21.submit
condor_submit ./condorSub/cat0/gof_study_22.submit
condor_submit ./condorSub/cat1/gof_study_22.submit
condor_submit ./condorSub/cat0/gof_study_23.submit
condor_submit ./condorSub/cat1/gof_study_23.submit
condor_submit ./condorSub/cat0/gof_study_24.submit
condor_submit ./condorSub/cat1/gof_study_24.submit
condor_submit ./condorSub/cat0/gof_study_25.submit
condor_submit ./condorSub/cat1/gof_study_25.submit
condor_submit ./condorSub/cat0/gof_study_26.submit
condor_submit ./condorSub/cat1/gof_study_26.submit
condor_submit ./condorSub/cat0/gof_study_27.submit
condor_submit ./condorSub/cat1/gof_study_27.submit
condor_submit ./condorSub/cat0/gof_study_28.submit
condor_submit ./condorSub/cat1/gof_study_28.submit
condor_submit ./condorSub/cat0/gof_study_29.submit
condor_submit ./condorSub/cat1/gof_study_29.submit
condor_submit ./condorSub/cat0/gof_study_30.submit
condor_submit ./condorSub/cat1/gof_study_30.submit
condor_submit ./condorSub/cat0/gof_study_31.submit
condor_submit ./condorSub/cat1/gof_study_31.submit
condor_submit ./condorSub/cat0/gof_study_32.submit
condor_submit ./condorSub/cat1/gof_study_32.submit
condor_submit ./condorSub/cat0/gof_study_33.submit
condor_submit ./condorSub/cat1/gof_study_33.submit
condor_submit ./condorSub/cat0/gof_study_34.submit
condor_submit ./condorSub/cat1/gof_study_34.submit
condor_submit ./condorSub/cat0/gof_study_35.submit
condor_submit ./condorSub/cat1/gof_study_35.submit
condor_submit ./condorSub/cat0/gof_study_36.submit
condor_submit ./condorSub/cat1/gof_study_36.submit
condor_submit ./condorSub/cat0/gof_study_37.submit
condor_submit ./condorSub/cat1/gof_study_37.submit
condor_submit ./condorSub/cat0/gof_study_38.submit
condor_submit ./condorSub/cat1/gof_study_38.submit
condor_submit ./condorSub/cat0/gof_study_39.submit
condor_submit ./condorSub/cat1/gof_study_39.submit
condor_submit ./condorSub/cat0/gof_study_40.submit
condor_submit ./condorSub/cat1/gof_study_40.submit
condor_submit ./condorSub/cat0/gof_study_41.submit
condor_submit ./condorSub/cat1/gof_study_41.submit
condor_submit ./condorSub/cat0/gof_study_42.submit
condor_submit ./condorSub/cat1/gof_study_42.submit
condor_submit ./condorSub/cat0/gof_study_43.submit
condor_submit ./condorSub/cat1/gof_study_43.submit
condor_submit ./condorSub/cat0/gof_study_44.submit
condor_submit ./condorSub/cat1/gof_study_44.submit
condor_submit ./condorSub/cat0/gof_study_45.submit
condor_submit ./condorSub/cat1/gof_study_45.submit
condor_submit ./condorSub/cat0/gof_study_46.submit
condor_submit ./condorSub/cat1/gof_study_46.submit
condor_submit ./condorSub/cat0/gof_study_47.submit
condor_submit ./condorSub/cat1/gof_study_47.submit
condor_submit ./condorSub/cat0/gof_study_48.submit
condor_submit ./condorSub/cat1/gof_study_48.submit
condor_submit ./condorSub/cat0/gof_study_49.submit
condor_submit ./condorSub/cat1/gof_study_49.submit
condor_submit ./condorSub/cat0/gof_study_50.submit
condor_submit ./condorSub/cat1/gof_study_50.submit
condor_submit ./condorSub/cat0/gof_study_51.submit
condor_submit ./condorSub/cat1/gof_study_51.submit
condor_submit ./condorSub/cat0/gof_study_52.submit
condor_submit ./condorSub/cat1/gof_study_52.submit
condor_submit ./condorSub/cat0/gof_study_53.submit
condor_submit ./condorSub/cat1/gof_study_53.submit
condor_submit ./condorSub/cat0/gof_study_54.submit
condor_submit ./condorSub/cat1/gof_study_54.submit
condor_submit ./condorSub/cat0/gof_study_55.submit
condor_submit ./condorSub/cat1/gof_study_55.submit
condor_submit ./condorSub/cat0/gof_study_56.submit
condor_submit ./condorSub/cat1/gof_study_56.submit
condor_submit ./condorSub/cat0/gof_study_57.submit
condor_submit ./condorSub/cat1/gof_study_57.submit
condor_submit ./condorSub/cat0/gof_study_58.submit
condor_submit ./condorSub/cat1/gof_study_58.submit
condor_submit ./condorSub/cat0/gof_study_59.submit
condor_submit ./condorSub/cat1/gof_study_59.submit
condor_submit ./condorSub/cat0/gof_study_60.submit
condor_submit ./condorSub/cat1/gof_study_60.submit
condor_submit ./condorSub/cat0/gof_study_61.submit
condor_submit ./condorSub/cat1/gof_study_61.submit
condor_submit ./condorSub/cat0/gof_study_62.submit
condor_submit ./condorSub/cat1/gof_study_62.submit
condor_submit ./condorSub/cat0/gof_study_63.submit
condor_submit ./condorSub/cat1/gof_study_63.submit
condor_submit ./condorSub/cat0/gof_study_64.submit
condor_submit ./condorSub/cat1/gof_study_64.submit
condor_submit ./condorSub/cat0/gof_study_65.submit
condor_submit ./condorSub/cat1/gof_study_65.submit
condor_submit ./condorSub/cat0/gof_study_66.submit
condor_submit ./condorSub/cat1/gof_study_66.submit
condor_submit ./condorSub/cat0/gof_study_67.submit
condor_submit ./condorSub/cat1/gof_study_67.submit
condor_submit ./condorSub/cat0/gof_study_68.submit
condor_submit ./condorSub/cat1/gof_study_68.submit
condor_submit ./condorSub/cat0/gof_study_69.submit
condor_submit ./condorSub/cat1/gof_study_69.submit
condor_submit ./condorSub/cat0/gof_study_70.submit
condor_submit ./condorSub/cat1/gof_study_70.submit
