echo "Freeze PDF 0"
combine -m 10.00 -M GenerateOnly window1_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat0
combine -m 12.25 -M GenerateOnly window2_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat0
combine -m 15.00 -M GenerateOnly window3_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat0
combine -m 18.50 -M GenerateOnly window4_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat0
combine -m 22.75 -M GenerateOnly window5_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat0
combine -m 27.75 -M GenerateOnly window6_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat0
combine -m 34.00 -M GenerateOnly window7_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat0
combine -m 41.75 -M GenerateOnly window8_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat0
combine -m 51.00 -M GenerateOnly window9_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat0
combine -m 62.25 -M GenerateOnly window10_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat0
mv higgsCombineFreeze0Cat0.GenerateOnly.* freezepdf0_cat0/

combine -m 10.00 -M GenerateOnly window1_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat1
combine -m 12.25 -M GenerateOnly window2_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat1
combine -m 15.00 -M GenerateOnly window3_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat1
combine -m 18.50 -M GenerateOnly window4_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat1
combine -m 22.75 -M GenerateOnly window5_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat1
combine -m 27.75 -M GenerateOnly window6_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat1
combine -m 34.00 -M GenerateOnly window7_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat1
combine -m 41.75 -M GenerateOnly window8_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat1
combine -m 51.00 -M GenerateOnly window9_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat1
combine -m 62.25 -M GenerateOnly window10_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=0 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze0Cat1
mv higgsCombineFreeze0Cat1.GenerateOnly.* freezepdf0_cat1/

echo "Freeze PDF 1"
combine -m 10.00 -M GenerateOnly window1_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat0
combine -m 12.25 -M GenerateOnly window2_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat0
combine -m 15.00 -M GenerateOnly window3_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat0
combine -m 18.50 -M GenerateOnly window4_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat0
combine -m 22.75 -M GenerateOnly window5_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat0
combine -m 27.75 -M GenerateOnly window6_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat0
combine -m 34.00 -M GenerateOnly window7_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat0
combine -m 41.75 -M GenerateOnly window8_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat0
combine -m 51.00 -M GenerateOnly window9_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat0
combine -m 62.25 -M GenerateOnly window10_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat0
mv higgsCombineFreeze1Cat0.GenerateOnly.* freezepdf1_cat0/

combine -m 10.00 -M GenerateOnly window1_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat1
combine -m 12.25 -M GenerateOnly window2_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat1
combine -m 15.00 -M GenerateOnly window3_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat1
combine -m 18.50 -M GenerateOnly window4_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat1
combine -m 22.75 -M GenerateOnly window5_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat1
combine -m 27.75 -M GenerateOnly window6_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat1
combine -m 34.00 -M GenerateOnly window7_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat1
combine -m 41.75 -M GenerateOnly window8_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat1
combine -m 51.00 -M GenerateOnly window9_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat1
combine -m 62.25 -M GenerateOnly window10_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=1 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze1Cat1
mv higgsCombineFreeze1Cat1.GenerateOnly.* freezepdf1_cat1/

echo "Freeze PDF 2"
combine -m 10.00 -M GenerateOnly window1_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat0
combine -m 12.25 -M GenerateOnly window2_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat0
combine -m 15.00 -M GenerateOnly window3_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat0
combine -m 18.50 -M GenerateOnly window4_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat0
combine -m 22.75 -M GenerateOnly window5_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat0
combine -m 27.75 -M GenerateOnly window6_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat0
combine -m 34.00 -M GenerateOnly window7_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat0
combine -m 41.75 -M GenerateOnly window8_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat0
combine -m 51.00 -M GenerateOnly window9_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat0
combine -m 62.25 -M GenerateOnly window10_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat0
mv higgsCombineFreeze2Cat0.GenerateOnly.* freezepdf2_cat0/

combine -m 10.00 -M GenerateOnly window1_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat1
combine -m 12.25 -M GenerateOnly window2_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat1
combine -m 15.00 -M GenerateOnly window3_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat1
combine -m 18.50 -M GenerateOnly window4_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat1
combine -m 22.75 -M GenerateOnly window5_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat1
combine -m 27.75 -M GenerateOnly window6_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat1
combine -m 34.00 -M GenerateOnly window7_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat1
combine -m 41.75 -M GenerateOnly window8_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat1
combine -m 51.00 -M GenerateOnly window9_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat1
combine -m 62.25 -M GenerateOnly window10_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=2 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze2Cat1
mv higgsCombineFreeze2Cat1.GenerateOnly.* freezepdf2_cat1/

echo "Freeze PDF 3"
combine -m 10.00 -M GenerateOnly window1_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat0
combine -m 12.25 -M GenerateOnly window2_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat0
combine -m 15.00 -M GenerateOnly window3_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat0
combine -m 18.50 -M GenerateOnly window4_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat0
combine -m 22.75 -M GenerateOnly window5_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat0
combine -m 27.75 -M GenerateOnly window6_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat0
combine -m 34.00 -M GenerateOnly window7_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat0
combine -m 41.75 -M GenerateOnly window8_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat0
combine -m 51.00 -M GenerateOnly window9_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat0
combine -m 62.25 -M GenerateOnly window10_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat0
mv higgsCombineFreeze3Cat0.GenerateOnly.* freezepdf3_cat0/

combine -m 10.00 -M GenerateOnly window1_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat1
combine -m 12.25 -M GenerateOnly window2_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat1
combine -m 15.00 -M GenerateOnly window3_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat1
combine -m 18.50 -M GenerateOnly window4_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat1
combine -m 22.75 -M GenerateOnly window5_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat1
combine -m 27.75 -M GenerateOnly window6_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat1
combine -m 34.00 -M GenerateOnly window7_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat1
combine -m 41.75 -M GenerateOnly window8_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat1
combine -m 51.00 -M GenerateOnly window9_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat1
combine -m 62.25 -M GenerateOnly window10_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=3 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze3Cat1
mv higgsCombineFreeze3Cat1.GenerateOnly.* freezepdf3_cat1/

echo "Freeze PDF 4"
combine -m 10.00 -M GenerateOnly window1_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat0
combine -m 12.25 -M GenerateOnly window2_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat0
combine -m 15.00 -M GenerateOnly window3_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat0
combine -m 18.50 -M GenerateOnly window4_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat0
combine -m 22.75 -M GenerateOnly window5_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat0
combine -m 27.75 -M GenerateOnly window6_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat0
combine -m 34.00 -M GenerateOnly window7_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat0
combine -m 41.75 -M GenerateOnly window8_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat0
combine -m 51.00 -M GenerateOnly window9_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat0
combine -m 62.25 -M GenerateOnly window10_cat0.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_0_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat0
mv higgsCombineFreeze4Cat0.GenerateOnly.* freezepdf4_cat0/

combine -m 10.00 -M GenerateOnly window1_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat1
combine -m 12.25 -M GenerateOnly window2_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat1
combine -m 15.00 -M GenerateOnly window3_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat1
combine -m 18.50 -M GenerateOnly window4_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat1
combine -m 22.75 -M GenerateOnly window5_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat1
combine -m 27.75 -M GenerateOnly window6_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat1
combine -m 34.00 -M GenerateOnly window7_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat1
combine -m 41.75 -M GenerateOnly window8_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat1
combine -m 51.00 -M GenerateOnly window9_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat1
combine -m 62.25 -M GenerateOnly window10_cat1.txt --expectSignal=0 --setParameters pdfindex_UntaggedTag_1_2018_13TeV=4 --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n Freeze4Cat1
mv higgsCombineFreeze4Cat1.GenerateOnly.* freezepdf4_cat1/

echo "Envelope"
combine -m 10.00 -M GenerateOnly window1_cat0.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat0
combine -m 12.25 -M GenerateOnly window2_cat0.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat0
combine -m 15.00 -M GenerateOnly window3_cat0.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat0
combine -m 18.50 -M GenerateOnly window4_cat0.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat0
combine -m 22.75 -M GenerateOnly window5_cat0.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat0
combine -m 27.75 -M GenerateOnly window6_cat0.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat0
combine -m 34.00 -M GenerateOnly window7_cat0.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat0
combine -m 41.75 -M GenerateOnly window8_cat0.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat0
combine -m 51.00 -M GenerateOnly window9_cat0.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat0
combine -m 62.25 -M GenerateOnly window10_cat0.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_0_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat0
mv higgsCombineEnvelopeCat0.GenerateOnly.* envelope_cat0/

combine -m 10.00 -M GenerateOnly window1_cat1.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat1
combine -m 12.25 -M GenerateOnly window2_cat1.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat1
combine -m 15.00 -M GenerateOnly window3_cat1.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat1
combine -m 18.50 -M GenerateOnly window4_cat1.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat1
combine -m 22.75 -M GenerateOnly window5_cat1.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat1
combine -m 27.75 -M GenerateOnly window6_cat1.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat1
combine -m 34.00 -M GenerateOnly window7_cat1.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat1
combine -m 41.75 -M GenerateOnly window8_cat1.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat1
combine -m 51.00 -M GenerateOnly window9_cat1.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat1
combine -m 62.25 -M GenerateOnly window10_cat1.txt --expectSignal=0  --freezeParameters MH,pdfindex_UntaggedTag_1_2018_13TeV  --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParams --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --saveToys -n EnvelopeCat1
mv higgsCombineEnvelopeCat1.GenerateOnly.* envelope_cat1/

echo "Done"
