echo "FREEZE 0"
combine -m 10.00 -M FitDiagnostics window1_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat0/higgsCombineFreeze0Cat0.GenerateOnly.mH10.123456.root --keepFailures -n Freeze0Cat0W1
combine -m 12.25 -M FitDiagnostics window2_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat0/higgsCombineFreeze0Cat0.GenerateOnly.mH12.25.123456.root --keepFailures -n Freeze0Cat0W2
combine -m 15.00 -M FitDiagnostics window3_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat0/higgsCombineFreeze0Cat0.GenerateOnly.mH15.123456.root --keepFailures -n Freeze0Cat0W3
combine -m 18.50 -M FitDiagnostics window4_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat0/higgsCombineFreeze0Cat0.GenerateOnly.mH18.5.123456.root --keepFailures -n Freeze0Cat0W4
combine -m 22.75 -M FitDiagnostics window5_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat0/higgsCombineFreeze0Cat0.GenerateOnly.mH22.75.123456.root --keepFailures -n Freeze0Cat0W5
combine -m 27.75 -M FitDiagnostics window6_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat0/higgsCombineFreeze0Cat0.GenerateOnly.mH27.75.123456.root --keepFailures -n Freeze0Cat0W6
combine -m 34.00 -M FitDiagnostics window7_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat0/higgsCombineFreeze0Cat0.GenerateOnly.mH34.123456.root --keepFailures -n Freeze0Cat0W7
combine -m 41.75 -M FitDiagnostics window8_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat0/higgsCombineFreeze0Cat0.GenerateOnly.mH41.75.123456.root --keepFailures -n Freeze0Cat0W8
combine -m 51.00 -M FitDiagnostics window9_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat0/higgsCombineFreeze0Cat0.GenerateOnly.mH51.123456.root --keepFailures -n Freeze0Cat0W9
combine -m 62.25 -M FitDiagnostics window10_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat0/higgsCombineFreeze0Cat0.GenerateOnly.mH62.25.123456.root --keepFailures -n Freeze0Cat0W10

mv higgsCombineFreeze0Cat0*.FitDiagnostics.*.123456.root freezepdf0_cat0/
mv fitDiagnosticsFreeze0Cat0*.root freezepdf0_cat0/

combine -m 10.00 -M FitDiagnostics window1_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat1/higgsCombineFreeze0Cat1.GenerateOnly.mH10.123456.root --keepFailures -n Freeze0Cat1W1
combine -m 12.25 -M FitDiagnostics window2_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat1/higgsCombineFreeze0Cat1.GenerateOnly.mH12.25.123456.root --keepFailures -n Freeze0Cat1W2
combine -m 15.00 -M FitDiagnostics window3_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat1/higgsCombineFreeze0Cat1.GenerateOnly.mH15.123456.root --keepFailures -n Freeze0Cat1W3
combine -m 18.50 -M FitDiagnostics window4_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat1/higgsCombineFreeze0Cat1.GenerateOnly.mH18.5.123456.root --keepFailures -n Freeze0Cat1W4
combine -m 22.75 -M FitDiagnostics window5_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat1/higgsCombineFreeze0Cat1.GenerateOnly.mH22.75.123456.root --keepFailures -n Freeze0Cat1W5
combine -m 27.75 -M FitDiagnostics window6_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat1/higgsCombineFreeze0Cat1.GenerateOnly.mH27.75.123456.root --keepFailures -n Freeze0Cat1W6
combine -m 34.00 -M FitDiagnostics window7_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat1/higgsCombineFreeze0Cat1.GenerateOnly.mH34.123456.root --keepFailures -n Freeze0Cat1W7
combine -m 41.75 -M FitDiagnostics window8_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat1/higgsCombineFreeze0Cat1.GenerateOnly.mH41.75.123456.root --keepFailures -n Freeze0Cat1W8
combine -m 51.00 -M FitDiagnostics window9_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat1/higgsCombineFreeze0Cat1.GenerateOnly.mH51.123456.root --keepFailures -n Freeze0Cat1W9
combine -m 62.25 -M FitDiagnostics window10_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf0_cat1/higgsCombineFreeze0Cat1.GenerateOnly.mH62.25.123456.root --keepFailures -n Freeze0Cat1W10

mv higgsCombineFreeze0Cat1*.FitDiagnostics.*.123456.root freezepdf0_cat1/
mv fitDiagnosticsFreeze0Cat1*.root freezepdf0_cat1/

echo "FREEZE 1"
combine -m 10.00 -M FitDiagnostics window1_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat0/higgsCombineFreeze1Cat0.GenerateOnly.mH10.123456.root --keepFailures -n Freeze1Cat0W1
combine -m 12.25 -M FitDiagnostics window2_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat0/higgsCombineFreeze1Cat0.GenerateOnly.mH12.25.123456.root --keepFailures -n Freeze1Cat0W2
combine -m 15.00 -M FitDiagnostics window3_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat0/higgsCombineFreeze1Cat0.GenerateOnly.mH15.123456.root --keepFailures -n Freeze1Cat0W3
combine -m 18.50 -M FitDiagnostics window4_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat0/higgsCombineFreeze1Cat0.GenerateOnly.mH18.5.123456.root --keepFailures -n Freeze1Cat0W4
combine -m 22.75 -M FitDiagnostics window5_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat0/higgsCombineFreeze1Cat0.GenerateOnly.mH22.75.123456.root --keepFailures -n Freeze1Cat0W5
combine -m 27.75 -M FitDiagnostics window6_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat0/higgsCombineFreeze1Cat0.GenerateOnly.mH27.75.123456.root --keepFailures -n Freeze1Cat0W6
combine -m 34.00 -M FitDiagnostics window7_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat0/higgsCombineFreeze1Cat0.GenerateOnly.mH34.123456.root --keepFailures -n Freeze1Cat0W7
combine -m 41.75 -M FitDiagnostics window8_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat0/higgsCombineFreeze1Cat0.GenerateOnly.mH41.75.123456.root --keepFailures -n Freeze1Cat0W8
combine -m 51.00 -M FitDiagnostics window9_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat0/higgsCombineFreeze1Cat0.GenerateOnly.mH51.123456.root --keepFailures -n Freeze1Cat0W9
combine -m 62.25 -M FitDiagnostics window10_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat0/higgsCombineFreeze1Cat0.GenerateOnly.mH62.25.123456.root --keepFailures -n Freeze1Cat0W10

mv higgsCombineFreeze1Cat0*.FitDiagnostics.*.123456.root freezepdf1_cat0/
mv fitDiagnosticsFreeze1Cat0*.root freezepdf1_cat0/

combine -m 10.00 -M FitDiagnostics window1_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat1/higgsCombineFreeze1Cat1.GenerateOnly.mH10.123456.root --keepFailures -n Freeze1Cat1W1
combine -m 12.25 -M FitDiagnostics window2_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat1/higgsCombineFreeze1Cat1.GenerateOnly.mH12.25.123456.root --keepFailures -n Freeze1Cat1W2
combine -m 15.00 -M FitDiagnostics window3_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat1/higgsCombineFreeze1Cat1.GenerateOnly.mH15.123456.root --keepFailures -n Freeze1Cat1W3
combine -m 18.50 -M FitDiagnostics window4_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat1/higgsCombineFreeze1Cat1.GenerateOnly.mH18.5.123456.root --keepFailures -n Freeze1Cat1W4
combine -m 22.75 -M FitDiagnostics window5_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat1/higgsCombineFreeze1Cat1.GenerateOnly.mH22.75.123456.root --keepFailures -n Freeze1Cat1W5
combine -m 27.75 -M FitDiagnostics window6_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat1/higgsCombineFreeze1Cat1.GenerateOnly.mH27.75.123456.root --keepFailures -n Freeze1Cat1W6
combine -m 34.00 -M FitDiagnostics window7_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat1/higgsCombineFreeze1Cat1.GenerateOnly.mH34.123456.root --keepFailures -n Freeze1Cat1W7
combine -m 41.75 -M FitDiagnostics window8_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat1/higgsCombineFreeze1Cat1.GenerateOnly.mH41.75.123456.root --keepFailures -n Freeze1Cat1W8
combine -m 51.00 -M FitDiagnostics window9_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat1/higgsCombineFreeze1Cat1.GenerateOnly.mH51.123456.root --keepFailures -n Freeze1Cat1W9
combine -m 62.25 -M FitDiagnostics window10_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf1_cat1/higgsCombineFreeze1Cat1.GenerateOnly.mH62.25.123456.root --keepFailures -n Freeze1Cat1W10

mv higgsCombineFreeze1Cat1*.FitDiagnostics.*.123456.root freezepdf1_cat1/
mv fitDiagnosticsFreeze1Cat1*.root freezepdf1_cat1/

echo "FREEZE 2"
combine -m 10.00 -M FitDiagnostics window1_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat0/higgsCombineFreeze2Cat0.GenerateOnly.mH10.123456.root --keepFailures -n Freeze2Cat0W1
combine -m 12.25 -M FitDiagnostics window2_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat0/higgsCombineFreeze2Cat0.GenerateOnly.mH12.25.123456.root --keepFailures -n Freeze2Cat0W2
combine -m 15.00 -M FitDiagnostics window3_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat0/higgsCombineFreeze2Cat0.GenerateOnly.mH15.123456.root --keepFailures -n Freeze2Cat0W3
combine -m 18.50 -M FitDiagnostics window4_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat0/higgsCombineFreeze2Cat0.GenerateOnly.mH18.5.123456.root --keepFailures -n Freeze2Cat0W4
combine -m 22.75 -M FitDiagnostics window5_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat0/higgsCombineFreeze2Cat0.GenerateOnly.mH22.75.123456.root --keepFailures -n Freeze2Cat0W5
combine -m 27.75 -M FitDiagnostics window6_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat0/higgsCombineFreeze2Cat0.GenerateOnly.mH27.75.123456.root --keepFailures -n Freeze2Cat0W6
combine -m 34.00 -M FitDiagnostics window7_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat0/higgsCombineFreeze2Cat0.GenerateOnly.mH34.123456.root --keepFailures -n Freeze2Cat0W7
combine -m 41.75 -M FitDiagnostics window8_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat0/higgsCombineFreeze2Cat0.GenerateOnly.mH41.75.123456.root --keepFailures -n Freeze2Cat0W8
combine -m 51.00 -M FitDiagnostics window9_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat0/higgsCombineFreeze2Cat0.GenerateOnly.mH51.123456.root --keepFailures -n Freeze2Cat0W9
combine -m 62.25 -M FitDiagnostics window10_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat0/higgsCombineFreeze2Cat0.GenerateOnly.mH62.25.123456.root --keepFailures -n Freeze2Cat0W10

mv higgsCombineFreeze2Cat0*.FitDiagnostics.*.123456.root freezepdf2_cat0/
mv fitDiagnosticsFreeze2Cat0*.root freezepdf2_cat0/

combine -m 10.00 -M FitDiagnostics window1_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat1/higgsCombineFreeze2Cat1.GenerateOnly.mH10.123456.root --keepFailures -n Freeze2Cat1W1
combine -m 12.25 -M FitDiagnostics window2_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat1/higgsCombineFreeze2Cat1.GenerateOnly.mH12.25.123456.root --keepFailures -n Freeze2Cat1W2
combine -m 15.00 -M FitDiagnostics window3_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat1/higgsCombineFreeze2Cat1.GenerateOnly.mH15.123456.root --keepFailures -n Freeze2Cat1W3
combine -m 18.50 -M FitDiagnostics window4_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat1/higgsCombineFreeze2Cat1.GenerateOnly.mH18.5.123456.root --keepFailures -n Freeze2Cat1W4
combine -m 22.75 -M FitDiagnostics window5_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat1/higgsCombineFreeze2Cat1.GenerateOnly.mH22.75.123456.root --keepFailures -n Freeze2Cat1W5
combine -m 27.75 -M FitDiagnostics window6_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat1/higgsCombineFreeze2Cat1.GenerateOnly.mH27.75.123456.root --keepFailures -n Freeze2Cat1W6
combine -m 34.00 -M FitDiagnostics window7_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat1/higgsCombineFreeze2Cat1.GenerateOnly.mH34.123456.root --keepFailures -n Freeze2Cat1W7
combine -m 41.75 -M FitDiagnostics window8_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat1/higgsCombineFreeze2Cat1.GenerateOnly.mH41.75.123456.root --keepFailures -n Freeze2Cat1W8
combine -m 51.00 -M FitDiagnostics window9_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat1/higgsCombineFreeze2Cat1.GenerateOnly.mH51.123456.root --keepFailures -n Freeze2Cat1W9
combine -m 62.25 -M FitDiagnostics window10_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf2_cat1/higgsCombineFreeze2Cat1.GenerateOnly.mH62.25.123456.root --keepFailures -n Freeze2Cat1W10

mv higgsCombineFreeze2Cat1*.FitDiagnostics.*.123456.root freezepdf2_cat1/
mv fitDiagnosticsFreeze2Cat1*.root freezepdf2_cat1/

echo "FREEZE 3"
combine -m 10.00 -M FitDiagnostics window1_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat0/higgsCombineFreeze3Cat0.GenerateOnly.mH10.123456.root --keepFailures -n Freeze3Cat0W1
combine -m 12.25 -M FitDiagnostics window2_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat0/higgsCombineFreeze3Cat0.GenerateOnly.mH12.25.123456.root --keepFailures -n Freeze3Cat0W2
combine -m 15.00 -M FitDiagnostics window3_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat0/higgsCombineFreeze3Cat0.GenerateOnly.mH15.123456.root --keepFailures -n Freeze3Cat0W3
combine -m 18.50 -M FitDiagnostics window4_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat0/higgsCombineFreeze3Cat0.GenerateOnly.mH18.5.123456.root --keepFailures -n Freeze3Cat0W4
combine -m 22.75 -M FitDiagnostics window5_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat0/higgsCombineFreeze3Cat0.GenerateOnly.mH22.75.123456.root --keepFailures -n Freeze3Cat0W5
combine -m 27.75 -M FitDiagnostics window6_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat0/higgsCombineFreeze3Cat0.GenerateOnly.mH27.75.123456.root --keepFailures -n Freeze3Cat0W6
combine -m 34.00 -M FitDiagnostics window7_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat0/higgsCombineFreeze3Cat0.GenerateOnly.mH34.123456.root --keepFailures -n Freeze3Cat0W7
combine -m 41.75 -M FitDiagnostics window8_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat0/higgsCombineFreeze3Cat0.GenerateOnly.mH41.75.123456.root --keepFailures -n Freeze3Cat0W8
combine -m 51.00 -M FitDiagnostics window9_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat0/higgsCombineFreeze3Cat0.GenerateOnly.mH51.123456.root --keepFailures -n Freeze3Cat0W9
combine -m 62.25 -M FitDiagnostics window10_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat0/higgsCombineFreeze3Cat0.GenerateOnly.mH62.25.123456.root --keepFailures -n Freeze3Cat0W10

mv higgsCombineFreeze3Cat0*.FitDiagnostics.*.123456.root freezepdf3_cat0/
mv fitDiagnosticsFreeze3Cat0*.root freezepdf3_cat0/

combine -m 10.00 -M FitDiagnostics window1_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat1/higgsCombineFreeze3Cat1.GenerateOnly.mH10.123456.root --keepFailures -n Freeze3Cat1W1
combine -m 12.25 -M FitDiagnostics window2_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat1/higgsCombineFreeze3Cat1.GenerateOnly.mH12.25.123456.root --keepFailures -n Freeze3Cat1W2
combine -m 15.00 -M FitDiagnostics window3_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat1/higgsCombineFreeze3Cat1.GenerateOnly.mH15.123456.root --keepFailures -n Freeze3Cat1W3
combine -m 18.50 -M FitDiagnostics window4_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat1/higgsCombineFreeze3Cat1.GenerateOnly.mH18.5.123456.root --keepFailures -n Freeze3Cat1W4
combine -m 22.75 -M FitDiagnostics window5_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat1/higgsCombineFreeze3Cat1.GenerateOnly.mH22.75.123456.root --keepFailures -n Freeze3Cat1W5
combine -m 27.75 -M FitDiagnostics window6_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat1/higgsCombineFreeze3Cat1.GenerateOnly.mH27.75.123456.root --keepFailures -n Freeze3Cat1W6
combine -m 34.00 -M FitDiagnostics window7_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat1/higgsCombineFreeze3Cat1.GenerateOnly.mH34.123456.root --keepFailures -n Freeze3Cat1W7
combine -m 41.75 -M FitDiagnostics window8_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat1/higgsCombineFreeze3Cat1.GenerateOnly.mH41.75.123456.root --keepFailures -n Freeze3Cat1W8
combine -m 51.00 -M FitDiagnostics window9_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat1/higgsCombineFreeze3Cat1.GenerateOnly.mH51.123456.root --keepFailures -n Freeze3Cat1W9
combine -m 62.25 -M FitDiagnostics window10_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf3_cat1/higgsCombineFreeze3Cat1.GenerateOnly.mH62.25.123456.root --keepFailures -n Freeze3Cat1W10

mv higgsCombineFreeze3Cat1*.FitDiagnostics.*.123456.root freezepdf3_cat1/
mv fitDiagnosticsFreeze3Cat1*.root freezepdf3_cat1/

echo "FREEZE 4"
combine -m 10.00 -M FitDiagnostics window1_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat0/higgsCombineFreeze4Cat0.GenerateOnly.mH10.123456.root --keepFailures -n Freeze4Cat0W1
combine -m 12.25 -M FitDiagnostics window2_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat0/higgsCombineFreeze4Cat0.GenerateOnly.mH12.25.123456.root --keepFailures -n Freeze4Cat0W2
combine -m 15.00 -M FitDiagnostics window3_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat0/higgsCombineFreeze4Cat0.GenerateOnly.mH15.123456.root --keepFailures -n Freeze4Cat0W3
combine -m 18.50 -M FitDiagnostics window4_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat0/higgsCombineFreeze4Cat0.GenerateOnly.mH18.5.123456.root --keepFailures -n Freeze4Cat0W4
combine -m 22.75 -M FitDiagnostics window5_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat0/higgsCombineFreeze4Cat0.GenerateOnly.mH22.75.123456.root --keepFailures -n Freeze4Cat0W5
combine -m 27.75 -M FitDiagnostics window6_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat0/higgsCombineFreeze4Cat0.GenerateOnly.mH27.75.123456.root --keepFailures -n Freeze4Cat0W6
combine -m 34.00 -M FitDiagnostics window7_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat0/higgsCombineFreeze4Cat0.GenerateOnly.mH34.123456.root --keepFailures -n Freeze4Cat0W7
combine -m 41.75 -M FitDiagnostics window8_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat0/higgsCombineFreeze4Cat0.GenerateOnly.mH41.75.123456.root --keepFailures -n Freeze4Cat0W8
combine -m 51.00 -M FitDiagnostics window9_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat0/higgsCombineFreeze4Cat0.GenerateOnly.mH51.123456.root --keepFailures -n Freeze4Cat0W9
combine -m 62.25 -M FitDiagnostics window10_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat0/higgsCombineFreeze4Cat0.GenerateOnly.mH62.25.123456.root --keepFailures -n Freeze4Cat0W10

mv higgsCombineFreeze4Cat0*.FitDiagnostics.*.123456.root freezepdf4_cat0/
mv fitDiagnosticsFreeze4Cat0*.root freezepdf4_cat0/

combine -m 10.00 -M FitDiagnostics window1_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat1/higgsCombineFreeze4Cat1.GenerateOnly.mH10.123456.root --keepFailures -n Freeze4Cat1W1
combine -m 12.25 -M FitDiagnostics window2_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat1/higgsCombineFreeze4Cat1.GenerateOnly.mH12.25.123456.root --keepFailures -n Freeze4Cat1W2
combine -m 15.00 -M FitDiagnostics window3_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat1/higgsCombineFreeze4Cat1.GenerateOnly.mH15.123456.root --keepFailures -n Freeze4Cat1W3
combine -m 18.50 -M FitDiagnostics window4_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat1/higgsCombineFreeze4Cat1.GenerateOnly.mH18.5.123456.root --keepFailures -n Freeze4Cat1W4
combine -m 22.75 -M FitDiagnostics window5_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat1/higgsCombineFreeze4Cat1.GenerateOnly.mH22.75.123456.root --keepFailures -n Freeze4Cat1W5
combine -m 27.75 -M FitDiagnostics window6_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat1/higgsCombineFreeze4Cat1.GenerateOnly.mH27.75.123456.root --keepFailures -n Freeze4Cat1W6
combine -m 34.00 -M FitDiagnostics window7_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat1/higgsCombineFreeze4Cat1.GenerateOnly.mH34.123456.root --keepFailures -n Freeze4Cat1W7
combine -m 41.75 -M FitDiagnostics window8_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat1/higgsCombineFreeze4Cat1.GenerateOnly.mH41.75.123456.root --keepFailures -n Freeze4Cat1W8
combine -m 51.00 -M FitDiagnostics window9_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat1/higgsCombineFreeze4Cat1.GenerateOnly.mH51.123456.root --keepFailures -n Freeze4Cat1W9
combine -m 62.25 -M FitDiagnostics window10_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile freezepdf4_cat1/higgsCombineFreeze4Cat1.GenerateOnly.mH62.25.123456.root --keepFailures -n Freeze4Cat1W10

mv higgsCombineFreeze4Cat1*.FitDiagnostics.*.123456.root freezepdf4_cat1/
mv fitDiagnosticsFreeze4Cat1*.root freezepdf4_cat1/

echo "ENVELOPE"
combine -m 10.00 -M FitDiagnostics window1_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat0/higgsCombineEnvelopeCat0.GenerateOnly.mH10.123456.root --keepFailures -n EnvelopeCat0W1
combine -m 12.25 -M FitDiagnostics window2_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat0/higgsCombineEnvelopeCat0.GenerateOnly.mH12.25.123456.root --keepFailures -n EnvelopeCat0W2
combine -m 15.00 -M FitDiagnostics window3_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat0/higgsCombineEnvelopeCat0.GenerateOnly.mH15.123456.root --keepFailures -n EnvelopeCat0W3
combine -m 18.50 -M FitDiagnostics window4_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat0/higgsCombineEnvelopeCat0.GenerateOnly.mH18.5.123456.root --keepFailures -n EnvelopeCat0W4
combine -m 22.75 -M FitDiagnostics window5_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat0/higgsCombineEnvelopeCat0.GenerateOnly.mH22.75.123456.root --keepFailures -n EnvelopeCat0W5
combine -m 27.75 -M FitDiagnostics window6_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat0/higgsCombineEnvelopeCat0.GenerateOnly.mH27.75.123456.root --keepFailures -n EnvelopeCat0W6
combine -m 34.00 -M FitDiagnostics window7_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat0/higgsCombineEnvelopeCat0.GenerateOnly.mH34.123456.root --keepFailures -n EnvelopeCat0W7
combine -m 41.75 -M FitDiagnostics window8_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat0/higgsCombineEnvelopeCat0.GenerateOnly.mH41.75.123456.root --keepFailures -n EnvelopeCat0W8
combine -m 51.00 -M FitDiagnostics window9_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat0/higgsCombineEnvelopeCat0.GenerateOnly.mH51.123456.root --keepFailures -n EnvelopeCat0W9
combine -m 62.25 -M FitDiagnostics window10_cat0.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat0/higgsCombineEnvelopeCat0.GenerateOnly.mH62.25.123456.root --keepFailures -n EnvelopeCat0W10

mv higgsCombineEnvelopeCat0*.FitDiagnostics.*.123456.root envelope_cat0/
mv fitDiagnosticsEnvelopeCat0*.root envelope_cat0/

combine -m 10.00 -M FitDiagnostics window1_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat1/higgsCombineEnvelopeCat1.GenerateOnly.mH10.123456.root --keepFailures -n EnvelopeCat1W1
combine -m 12.25 -M FitDiagnostics window2_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat1/higgsCombineEnvelopeCat1.GenerateOnly.mH12.25.123456.root --keepFailures -n EnvelopeCat1W2
combine -m 15.00 -M FitDiagnostics window3_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat1/higgsCombineEnvelopeCat1.GenerateOnly.mH15.123456.root --keepFailures -n EnvelopeCat1W3
combine -m 18.50 -M FitDiagnostics window4_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat1/higgsCombineEnvelopeCat1.GenerateOnly.mH18.5.123456.root --keepFailures -n EnvelopeCat1W4
combine -m 22.75 -M FitDiagnostics window5_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat1/higgsCombineEnvelopeCat1.GenerateOnly.mH22.75.123456.root --keepFailures -n EnvelopeCat1W5
combine -m 27.75 -M FitDiagnostics window6_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat1/higgsCombineEnvelopeCat1.GenerateOnly.mH27.75.123456.root --keepFailures -n EnvelopeCat1W6
combine -m 34.00 -M FitDiagnostics window7_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat1/higgsCombineEnvelopeCat1.GenerateOnly.mH34.123456.root --keepFailures -n EnvelopeCat1W7
combine -m 41.75 -M FitDiagnostics window8_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat1/higgsCombineEnvelopeCat1.GenerateOnly.mH41.75.123456.root --keepFailures -n EnvelopeCat1W8
combine -m 51.00 -M FitDiagnostics window9_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat1/higgsCombineEnvelopeCat1.GenerateOnly.mH51.123456.root --keepFailures -n EnvelopeCat1W9
combine -m 62.25 -M FitDiagnostics window10_cat1.txt --expectSignal=0 --freezeParameters MH --saveWorkspace --X-rtd MINIMIZER_freezeDisassociatedParam --rMin -10 --rMax 10  --cminDefaultMinimizerStrategy 0 -t 1000 --toysFrequentist --toysFile envelope_cat1/higgsCombineEnvelopeCat1.GenerateOnly.mH62.25.123456.root --keepFailures -n EnvelopeCat1W10

mv higgsCombineEnvelopeCat1*.FitDiagnostics.*.123456.root envelope_cat1/
mv fitDiagnosticsEnvelopeCat1*.root envelope_cat1/
echo "Done"
