condor_submit ./freezepdf0_cat0/bias_study_W1.submit
condor_submit ./freezepdf0_cat0/bias_study_W2.submit
condor_submit ./freezepdf0_cat0/bias_study_W3.submit
condor_submit ./freezepdf0_cat0/bias_study_W4.submit
condor_submit ./freezepdf0_cat0/bias_study_W5.submit
condor_submit ./freezepdf0_cat0/bias_study_W6.submit
condor_submit ./freezepdf0_cat0/bias_study_W7.submit
condor_submit ./freezepdf0_cat0/bias_study_W8.submit
condor_submit ./freezepdf0_cat0/bias_study_W9.submit
condor_submit ./freezepdf0_cat0/bias_study_W10.submit
condor_submit ./freezepdf0_cat1/bias_study_W1.submit
condor_submit ./freezepdf0_cat1/bias_study_W2.submit
condor_submit ./freezepdf0_cat1/bias_study_W3.submit
condor_submit ./freezepdf0_cat1/bias_study_W4.submit
condor_submit ./freezepdf0_cat1/bias_study_W5.submit
condor_submit ./freezepdf0_cat1/bias_study_W6.submit
condor_submit ./freezepdf0_cat1/bias_study_W7.submit
condor_submit ./freezepdf0_cat1/bias_study_W8.submit
condor_submit ./freezepdf0_cat1/bias_study_W9.submit
condor_submit ./freezepdf0_cat1/bias_study_W10.submit
condor_submit ./freezepdf1_cat0/bias_study_W1.submit
condor_submit ./freezepdf1_cat0/bias_study_W2.submit
condor_submit ./freezepdf1_cat0/bias_study_W3.submit
condor_submit ./freezepdf1_cat0/bias_study_W4.submit
condor_submit ./freezepdf1_cat0/bias_study_W5.submit
condor_submit ./freezepdf1_cat0/bias_study_W6.submit
condor_submit ./freezepdf1_cat0/bias_study_W7.submit
condor_submit ./freezepdf1_cat0/bias_study_W8.submit
condor_submit ./freezepdf1_cat0/bias_study_W9.submit
condor_submit ./freezepdf1_cat0/bias_study_W10.submit
condor_submit ./freezepdf1_cat1/bias_study_W1.submit
condor_submit ./freezepdf1_cat1/bias_study_W2.submit
condor_submit ./freezepdf1_cat1/bias_study_W3.submit
condor_submit ./freezepdf1_cat1/bias_study_W4.submit
condor_submit ./freezepdf1_cat1/bias_study_W5.submit
condor_submit ./freezepdf1_cat1/bias_study_W6.submit
condor_submit ./freezepdf1_cat1/bias_study_W7.submit
condor_submit ./freezepdf1_cat1/bias_study_W8.submit
condor_submit ./freezepdf1_cat1/bias_study_W9.submit
condor_submit ./freezepdf1_cat1/bias_study_W10.submit
condor_submit ./freezepdf2_cat0/bias_study_W1.submit
condor_submit ./freezepdf2_cat0/bias_study_W2.submit
condor_submit ./freezepdf2_cat0/bias_study_W3.submit
condor_submit ./freezepdf2_cat0/bias_study_W4.submit
condor_submit ./freezepdf2_cat0/bias_study_W5.submit
condor_submit ./freezepdf2_cat0/bias_study_W6.submit
condor_submit ./freezepdf2_cat0/bias_study_W7.submit
condor_submit ./freezepdf2_cat0/bias_study_W8.submit
condor_submit ./freezepdf2_cat0/bias_study_W9.submit
condor_submit ./freezepdf2_cat0/bias_study_W10.submit
condor_submit ./freezepdf2_cat1/bias_study_W1.submit
condor_submit ./freezepdf2_cat1/bias_study_W2.submit
condor_submit ./freezepdf2_cat1/bias_study_W3.submit
condor_submit ./freezepdf2_cat1/bias_study_W4.submit
condor_submit ./freezepdf2_cat1/bias_study_W5.submit
condor_submit ./freezepdf2_cat1/bias_study_W6.submit
condor_submit ./freezepdf2_cat1/bias_study_W7.submit
condor_submit ./freezepdf2_cat1/bias_study_W8.submit
condor_submit ./freezepdf2_cat1/bias_study_W9.submit
condor_submit ./freezepdf2_cat1/bias_study_W10.submit
condor_submit ./freezepdf3_cat0/bias_study_W1.submit
condor_submit ./freezepdf3_cat0/bias_study_W2.submit
condor_submit ./freezepdf3_cat0/bias_study_W3.submit
condor_submit ./freezepdf3_cat0/bias_study_W4.submit
condor_submit ./freezepdf3_cat0/bias_study_W5.submit
condor_submit ./freezepdf3_cat0/bias_study_W6.submit
condor_submit ./freezepdf3_cat0/bias_study_W7.submit
condor_submit ./freezepdf3_cat0/bias_study_W8.submit
condor_submit ./freezepdf3_cat0/bias_study_W9.submit
condor_submit ./freezepdf3_cat0/bias_study_W10.submit
condor_submit ./freezepdf3_cat1/bias_study_W1.submit
condor_submit ./freezepdf3_cat1/bias_study_W2.submit
condor_submit ./freezepdf3_cat1/bias_study_W3.submit
condor_submit ./freezepdf3_cat1/bias_study_W4.submit
condor_submit ./freezepdf3_cat1/bias_study_W5.submit
condor_submit ./freezepdf3_cat1/bias_study_W6.submit
condor_submit ./freezepdf3_cat1/bias_study_W7.submit
condor_submit ./freezepdf3_cat1/bias_study_W8.submit
condor_submit ./freezepdf3_cat1/bias_study_W9.submit
condor_submit ./freezepdf3_cat1/bias_study_W10.submit
condor_submit ./freezepdf4_cat0/bias_study_W1.submit
condor_submit ./freezepdf4_cat0/bias_study_W2.submit
condor_submit ./freezepdf4_cat0/bias_study_W3.submit
condor_submit ./freezepdf4_cat0/bias_study_W4.submit
condor_submit ./freezepdf4_cat0/bias_study_W5.submit
condor_submit ./freezepdf4_cat0/bias_study_W6.submit
condor_submit ./freezepdf4_cat0/bias_study_W7.submit
condor_submit ./freezepdf4_cat0/bias_study_W8.submit
condor_submit ./freezepdf4_cat0/bias_study_W9.submit
condor_submit ./freezepdf4_cat0/bias_study_W10.submit
condor_submit ./freezepdf4_cat1/bias_study_W1.submit
condor_submit ./freezepdf4_cat1/bias_study_W2.submit
condor_submit ./freezepdf4_cat1/bias_study_W3.submit
condor_submit ./freezepdf4_cat1/bias_study_W4.submit
condor_submit ./freezepdf4_cat1/bias_study_W5.submit
condor_submit ./freezepdf4_cat1/bias_study_W6.submit
condor_submit ./freezepdf4_cat1/bias_study_W7.submit
condor_submit ./freezepdf4_cat1/bias_study_W8.submit
condor_submit ./freezepdf4_cat1/bias_study_W9.submit
condor_submit ./freezepdf4_cat1/bias_study_W10.submit
condor_submit ./envelope_cat0/bias_study_W1.submit
condor_submit ./envelope_cat0/bias_study_W2.submit
condor_submit ./envelope_cat0/bias_study_W3.submit
condor_submit ./envelope_cat0/bias_study_W4.submit
condor_submit ./envelope_cat0/bias_study_W5.submit
condor_submit ./envelope_cat0/bias_study_W6.submit
condor_submit ./envelope_cat0/bias_study_W7.submit
condor_submit ./envelope_cat0/bias_study_W8.submit
condor_submit ./envelope_cat0/bias_study_W9.submit
condor_submit ./envelope_cat0/bias_study_W10.submit
condor_submit ./envelope_cat1/bias_study_W1.submit
condor_submit ./envelope_cat1/bias_study_W2.submit
condor_submit ./envelope_cat1/bias_study_W3.submit
condor_submit ./envelope_cat1/bias_study_W4.submit
condor_submit ./envelope_cat1/bias_study_W5.submit
condor_submit ./envelope_cat1/bias_study_W6.submit
condor_submit ./envelope_cat1/bias_study_W7.submit
condor_submit ./envelope_cat1/bias_study_W8.submit
condor_submit ./envelope_cat1/bias_study_W9.submit
condor_submit ./envelope_cat1/bias_study_W10.submit
